### PR TITLE
UniversalRed-Patch1

### PR DESCRIPTION
**Pull request by UniversalRed**
Fixed the Dutch Governments weird noideology government which resulted in a
crash whenever clicking to hold elections or to view parties within the
politics tab. Also, fixed the Dutch rebellion war to end in 1648. In addition, created a decision for China related to the economic reforms of 1978, which increases mining efficiency and size but decreases farm size and efficiency, as well as lowering factory costs and increasing factory output by 5.

### CODE REVIEW

**Comment by Palisight** [comment]
Integrated Dutch governments bug fixes. Thanks

I currently have the Dutch Rebellion ending with the start of the 12 years truce in the history files. Its better this way as eventually a scenario starting somewhere around the start of the 30 years war will be added and the Dutch Spain conflict won't re-start until 1622

As for Deng's reforms......shouldn't this be approached from the other angle? i.e. instead of giving Deng China bonuses, give Mao China penalties. Deng's reforms could 
A.) Remove Mao penalties
B.) Change the government from a proletarian dictatorship to a socialist republic with State Capitalism rather than Planned economy

Otherwise, this makes westernized China even more powerful than it already is.

**Comment by UniversalRed** [comment]
That's what I was thinking too. Maybe during the communist regime from the day Mao led it to the day he died there should be events like the great famine and such, and then after his death there should be events corresponding to Deng's economic reforms like stage 1 of the decollectivization of wheat and then stage 2 where the government changes economic policy to something like sate capitalism.

**Comment by UniversalRed** [comment]
I have yet to finish the 2nd reform, though that'll come at a later time since I don't understand how I can change the policy of a party in-game.

**Comment by Palisight** [comment]
As far as I'm aware, there is no way to change the policies of a party. That's why I mentioned changing from a proletarian dictatorship (Communist party) to a socialist republic (Socialist party).

The annoying part is that, given the dynamic nature of how the game works (China could go "Deng" earlier or later than it did historically), yet the dates political parties are available are set in stone

**Comment by UniversalRed** [comment]
I don't think I'll be able to pull off a proper switch between communist to socialist, but I could try.

**Comment by UniversalRed** [comment]
Finished up China's government switch event as Deng's second stage of economic reforms.

**Comment by Palisight** [comment]
The naval base/fort bug seems to be related to the ad_hoc modifiers that seem to be causing some people, but not all people trouble for some unknown reason

Basically the solution is to move the fort/naval base levels into the tech tree. The hard part is figuring out when important advances in fort/naval base construction occurred in real life and what techs they should be added to, which I haven't gotten around to doing yet

West Germany is just Germany in this mod. I've started giving the East German provinces to the Soviet Union in the 1946 scenario, but I haven't finished it, so Germany in the Cold War scenario doesn't look right at the moment. I'm planning on finishing the Germany/HRE rework by the end of the month

**Comment by UniversalRed** [comment]
Alright then, also, the Soviet Union seems to be pretty bare bone at the moment, even with the secret service modifier. Should I try to make some events that are centered around the secret service modifier within Russia? Such as eliminating populations in cities to reduce militancy, etc? Also, America is kind of in the same position as the USSR, so I plan on adding events relating to war on terror.

**Comment by Palisight** [comment]
Its one of those if you want to kind of things
If you do want to, make sure the pop eliminating events only occur during Stalinist USSR. Of course this creates the need to differentiate Stalinist USSR from Khrushchevian USSR, and of course brings up the "railroading problem", where people who want to ahistorically continue to play a Stalinist regime should be able to 

I personally don't get the appeal of modern day Victoria 2 scenarios, but if modeling the war of terror interests you, go right ahead

**Comment by UniversalRed** [comment]
Now that you mention it, I don't see the point either, mostly because the USA is in almost every single kind of war in modern day.

I'll be focusing some events/decisions on the USSR however.

Another thing is that the puppet event that the USSR gets at the start of the cold war aren't registered after the player quits/resigns the game. This is most likely a bug. In addition, it seems like Germany at the start of the cold war is actually under the sphere of the U.S. until the player leaves the game.

**Comment by UniversalRed** [comment]
That will be the last commit I'll be sending for the v0.613 release of the mod.

**Comment by Palisight** [comment]
Patch # 1 integrated into 0.613 WIP, so this pull request is being closed

Thank you for your CAN/RUS content additions and the crash bug fix

**Pull request closed without merging**
